# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stute_stat <- function(V) {
    .Call(`_StuteTest_stute_stat`, V)
}

stute_core <- function(X, y, F) {
    .Call(`_StuteTest_stute_core`, X, y, F)
}

